# Generated by Django 2.2.7 on 2019-11-11 19:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, null=True)),
                ('ingredients', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
                ('prep_time', models.CharField(max_length=10, null=True)),
                ('cook_time', models.CharField(max_length=10, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('keywords', models.TextField(null=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
