# Generated by Django 2.2.7 on 2019-12-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
